model:
  file: baseline
  name: EfficientNet_B0 # EfficientNetV2S, EfficientNet_B0
  strategy: Standard
  input_channels: 3

data:
  split:
    train: 0.8
    val: 0.1
    test: 0.1

training:
  epochs: 20
  batch_size: 32
  optimizer: Lion # Adam, AdamW, Lion
  learning_rate: 0.0001
  weight_decay: 0.01
  early_stopping: 10

experiment:
  n_ways: 50
  n_shots: 20
  dataset: CIFAR100

paths:
  data_dir: './data'
  weight_dir: './weights'
  log_dir: './logs'
