model:
  file: baseline
  name: EfficientNetV2S # EfficientNetV2S, EfficientNet_B0
  strategy: Standard
  input_channels: 1
  num_classes: 3
  resize: 84


training:
  epochs: 20
  batch_size: 32
  optimizer: Adam # Adam, AdamW, Lion
  learning_rate: 0.0001
  weight_decay: 0.01
  early_stopping: 5

experiment:
  dataset: SAR_class_3 # miniImageNet, Fewshot-CIFAR100, SAR_class_3, SAR_class_6

paths:
  dataset_dir: './data'
  weight_dir: './weights'
  log_dir: './logs'
